QuestionsAnswers/QuestionsAnswers/urls.py
from django.conf.urls import url, include, static
from django.contrib import admin
from django.conf import settings


urlpatterns = [
    # admin site
    url(r'^admin/', admin.site.urls, name='admin'),
    # homepage
    url(r'^', include('apps.homepage.urls'), name='homepage'),
    # authentication
    url(r'^auth/', include('apps.authentication.urls'), name='authentication'),
    # users
    url(r'^users/', include('apps.accounts.urls'), name='users'),
    # questions
    url(r'^questions/', include('apps.questions.urls'), name='questions'),
    # questions and answers
    url(r'^questions/(?P<question>\d+)/answers/', include('apps.answers.urls'), name='answers'),
] + static.static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

QuestionsAnswers/apps/accounts/urls.py
from django.conf.urls import url, include
from .views import AccountDetail, AccountUpdate, AccountDelete, ListUserAnswers, \
    ListUserQuestions

app_name = 'accounts'

urlpatterns = [
    # update, delete account, pk=id
    url(r'(?P<pk>\d+)/update/$', AccountUpdate.as_view(), name='update'),
    url(r'(?P<pk>\d+)/delete/$', AccountDelete.as_view(), name='delete'),
    # detail view account
    url(r'(?P<pk>\d+)/$', AccountDetail.as_view(), name='detail'),
    # user answers
    url(r'^(?P<pk>\d+)/answers/$', ListUserAnswers.as_view(), name='user_answers'),
    # user questions
    url(r'^(?P<pk>\d+)/questions/$', ListUserQuestions.as_view(), name='user_questions'),
]

QuestionsAnswers/apps/questions/urls.py
from django.conf.urls import url
from .views import CreateQuestion, UpdateQuestion, DeleteQuestion, ListQuestions, DetailQuestion


app_name = 'questions'
urlpatterns = [
    # all questions
    url(r'^all/$', ListQuestions.as_view(), name='all'),
    # create question
    url(r'^create/$', CreateQuestion.as_view(), name='create'),
    # update question
    url(r'^(?P<question>\d+)/update/$', UpdateQuestion.as_view(), name='update'),
    # delete question
    url(r'^(?P<question>\d+)/delete/$', DeleteQuestion.as_view(), name='delete'),
    # detail question
    url(r'^(?P<question>\d+)/detail/$', DetailQuestion.as_view(), name='detail'),

]

QuestionsAnswers/apps/accounts/models.py
from django.db import models
from django.core.mail import send_mail
from django.core.validators import EmailValidator, validate_email, validate_image_file_extension
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import PermissionsMixin
from django.conf import settings
from django.utils.translation import gettext_lazy as _
from .validators import validate_username, validate_last_name, validate_first_name


# get path for avatar
def upload_avatar_path(instance, file):
    # {0} - id user, {1} - filename
    return 'users/images/avatars/{0}/{1}'.format(str(instance.id), file)


# override manager user model
class UserManager(BaseUserManager):
    # create user method
    def _create_user(self, username, password, email, **extra):
        email = self.normalize_email(email)
        user = self.model(username=username, email=email, **extra)
        user.set_password(password)
        user.save(using=self._db)
        return user

    # set superuser fields false and return create func
    def create_user(self, username, password, email, **extra):
        extra.setdefault('is_superuser', False)
        return self._create_user(username, password, email, **extra)

    # creates superuser method
    def create_superuser(self, username, password, email, **extra):
        email = self.normalize_email(email)
        user = self._create_user(username, password, email, **extra)
        user.is_admin = True
        user.save(using=self._db)


# custom user model with permission mixin methods
class User(AbstractBaseUser, PermissionsMixin):
    # id field
    id = models.AutoField(_('id'), auto_created=True, primary_key=True)
    # username field
    username = models.CharField(_('username'),  max_length=32, db_column='username', unique=True,
                                help_text=_('Required. 32 character or fewer. Letters, digits and ./-/_ only.'),
                                validators=[validate_username],
                                error_messages={
                                    'unique': _('A user with this name already exists.'),
                                    'invalid': _('Enter a valid username.'),
                                })
    # email field
    email = models.EmailField(_('email'), max_length=254, db_column='email',
                              help_text=_('Required.'),
                              validators=[validate_email],
                              error_messages={
                                    'invalid': _('Enter a valid email address.'),
                                })
    # first_name field
    first_name = models.CharField(_('first name'), max_length=30, db_column='first_name', blank=True,
                                  help_text=_('Not required. 30 character or fewer. Letters and - only.'),
                                  validators=[validate_first_name],
                                  error_messages={
                                      'invalid': _('Enter a valid first name.')
                                  })
    # last_name field
    last_name = models.CharField(_('last name'), max_length=150, db_column='last_name', blank=True,
                                 help_text=_('Not required. 150 character or fewer. Letters and - only.'),
                                 validators=[validate_last_name],
                                 error_messages={
                                     'invalid': _('Enter a valid last name.')
                                 })
    # avatar field
    avatar = models.ImageField(_('avatar'), db_column='avatar', blank=True, upload_to=upload_avatar_path,
                               validators=[validate_image_file_extension],
                               error_messages={
                                   'invalid': _('Please choice a valid image format.'),
                               })
    # rating field
    rating = models.IntegerField(_('rating'), db_column='rating', default=0)
    # active field
    is_active = models.BooleanField(_('active'), default=True)
    # admin field
    is_admin = models.BooleanField(_('admin'), default=False)
    # date joined
    date_joined = models.DateTimeField(_('date joined'), db_column='date_joined', auto_now_add=True)
    # manager for model
    objects = UserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    class Meta:
        verbose_name = _('user')
        db_table = 'user'

    def __str__(self):
        return self.username

    # get first_name + last_name
    def get_full_name(self):
        return '{0} {1}'.format(self.first_name, self.last_name).strip()

    # get only first_name
    def get_short_name(self):
        return '{0}'.format(self.first_name).strip()

    def email_user(self, subject, message, from_email=None, **kwargs):
        return send_mail(subject, message, from_email, [self.email], **kwargs)

    # get avatar url or default avatar image
    def get_avatar_url(self):
        return self.avatar.url if self.avatar else settings.MEDIA_URL + 'default/avatar/default-avatar.png'

    # override save method
    def save(self, *args, **kwargs):
        # set avatar and call func upload_to of ImageField with ID object
        # create path with id object after save
        if self.id is None and self.avatar:
            image = self.avatar
            self.avatar = None
            super().save(*args, **kwargs)
            self.avatar = image
        return super().save(*args, **kwargs)

    # check user is staff or not
    @property
    def is_staff(self):
        return self.is_admin

QuestionsAnswers/apps/accounts/forms.py
from django import forms
from django.forms import ModelForm
from django.forms.widgets import ClearableFileInput
from .models import User
from django.utils.translation import gettext_lazy as _


# custom image field widget
class CustomImageFieldWidget(ClearableFileInput):
    # set template for fileinput widget
    template_name = 'specials/clearable_file_input.html'


# Update user form
class UserUpdateForm(ModelForm):
    # password
    password = forms.CharField(max_length=32, help_text=_('32 character or fewer.'),
                               required=True, label=_('Password'),
                               widget=forms.PasswordInput(attrs={'class': 'form-control-inline'}))

    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name', 'avatar')
        # set widgets with attrs
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control form-control-inline'}),
            'email': forms.EmailInput(attrs={'class': 'form-control form-control-inline'}),
            'first_name': forms.TextInput(attrs={'class': 'form-control form-control-inline'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control form-control-inline'}),
            'avatar': CustomImageFieldWidget(),
        }

    # override clean method for check password
    def clean_password(self):
        password = self.cleaned_data.get('password', '')
        if not self.instance.check_password(password):
            raise forms.ValidationError(_('Invalid password'))
        return password

QuestionsAnswers/apps/accounts/views.py
from django.shortcuts import redirect
from django.core.urlresolvers import resolve
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import UpdateView, DeleteView
from django.views.generic import DetailView, ListView
from django.utils.translation import gettext_lazy as _
from ..answers.models import Answer
from ..questions.models import Question
from .models import User
from .forms import UserUpdateForm


# mixin class for get object from pk
class AccountsMixin(object):
    def get_object(self, queryset=None):
        # get pk from kwargs and return user object
        return self.model.object.get(id=self.kwargs['pk'])


# override dispatch method for redirect
class AccountDispatchMixin(object):
    def dispatch(self, request, *args, **kwargs):
        # get user
        user = User.objects.get(id=kwargs['pk'])
        # user == request.user
        if user.id == request.user.id:
            return super().dispatch(request, *args, **kwargs)
        else:
            # Example:
            # this happened, if url - /accounts/9/ change to /accounts/10/ but user.id == 9
            # redirect to correct url for this user
            # this method only fo accounts
            url = resolve(request.path).url_name
            return redirect('accounts:' + str(url), pk=request.user.id)


# detail view account with login required ans mixin
class AccountDetail(AccountDispatchMixin, DetailView, AccountsMixin, LoginRequiredMixin):
    template_name = 'accounts/detail.html'
    model = User
    # setting for login required
    redirect_field_name = None
    login_url = '/'

    # get object in template
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['object'] = self.object
        # select object from table where user_id=self.object.id order by date_created desc limit 6
        context['questions'] = list(Question.objects.filter(user_id=self.object.id).order_by('-date_created')[:6])
        context['answers'] = list(Answer.objects.filter(user_id=self.object.id).order_by('-date_created')[:6])
        return context


# update view account with login required and mixin
class AccountUpdate(AccountDispatchMixin, UpdateView, AccountsMixin, LoginRequiredMixin):
    template_name = 'accounts/update.html'
    form_class = UserUpdateForm
    model = User
    success_url = 'accounts:detail'
    # settings for login required
    redirect_field_name = None
    login_url = '/'

    # override func success url
    def get_success_url(self):
        # return success url with pk
        return reverse_lazy(self.success_url, kwargs={'pk': self.object.pk})


# Delete view with login required ans mixin
class AccountDelete(AccountDispatchMixin, DeleteView, AccountsMixin, LoginRequiredMixin):
    model = User
    template_name = 'accounts/delete.html'
    success_url = '/'
    # settings for login required
    login_url = '/'
    redirect_field_name = None
    # custom field

    # override post method
    def post(self, request, *args, **kwargs):
        # set self.object
        self.object = self.get_object()
        # check password for user and if true return delete method
        if self.object.check_password(request.POST.get('password_confirm')):
            return self.delete(request, *args, **kwargs)
        else:
            # set error to context and response template
            context = super().get_context_data(**kwargs)
            context['error'] = _('Invalid password')
            return self.render_to_response(context=context)

    # override delete method for delete file image from path
    def delete(self, request, *args, **kwargs):
        self.object.avatar.delete(save=True)
        return super().delete(request, *args, **kwargs)


# list user answers
class ListUserAnswers(AccountDispatchMixin, ListView, LoginRequiredMixin):
    template_name = 'accounts/user_answers.html'
    model = Answer
    paginate_by = 5
    # login required settings
    login_url = '/'
    redirect_field_name = None

    # get queryset
    def get_queryset(self):
        return Answer.objects.filter(user_id=self.kwargs['pk'])


# list user questions
class ListUserQuestions(AccountDispatchMixin, ListView, LoginRequiredMixin):
    template_name = 'accounts/user_questions.html'
    model = Question
    paginate_by = 5
    # login required settings
    login_url = '/'
    redirect_field_name = None

    # get queryset
    def get_queryset(self):
        return Question.objects.filter(user_id=self.kwargs['pk'])

QuestionsAnswers/templates/accounts/delete.html
{% extends 'base.html' %}

{% block title %}Delete account{% endblock title %}

{% block content %}
<div class="col-md-6 col-md-offset-3">
    <form action="" method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete "{{ object.username }}"?</p>
        {% if error %}
            <div class="alert alert-warning alert-dismissible form-width" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times</span>
                </button>
                <strong>Error: </strong>{{ error }}
            </div>
        {% endif %}
        <label for="id_password">Password:</label>
        <span class="help-text text-info">Input your password</span>
        <div class="form-input">
            <input class="form-control form-width" type="password" id="id_password" name="password_confirm">
        </div>
        <input class="btn btn-default" type="submit" value="Confirm" />
        <a class="btn btn-link" href="{% url 'accounts:detail' request.user.pk %}" >Back</a>
    </form>
</div>
{% endblock content %}

QuestionsAnswers/templates/accounts/detail.html
{% extends 'base.html' %}

{% block title %}Account{% endblock title %}

{% block content %}
<div class="account-detail">
    <div class="col-md-4">
        <img class="img-rounded img-account" src="{{ object.get_avatar_url }}">
        <h1>{{ object.username }}</h1>
        <h2>{{ object.first_name }} {{ object.last_name }}</h2>
        <h4><p>On site with: {{ object.date_joined }}</p></h4>
        <h4>Rating: {{ object.rating }}</h4>
        {% if object.is_active %}
            <h3>On site: Online</h3>
        {% else %}
            <h3>On site: Offline</h3>
        {% endif %}

    </div>
    <div class="col-md-4">
        <h2>6 Last questions</h2>
        <div class="questions-area">
            {% for quest in questions %}
                <div class="questions">
                    <a href="{% url 'questions:detail' quest.pk %}"><h3>{{ quest.title|truncatechars:60 }}</h3></a>
                    <h4>Created: {{ quest.date_created }}</h4>
                </div>
            {% endfor %}
        </div>
    </div>
    <div class="col-md-4">
        <h2>6 last answers</h2>
        <div class="answers-area">
            {% for answer in answers %}
                <div class="answers">
                    <a href="{% url 'questions:detail' answer.question_id.pk %}"><h3>{{ answer.question_id.title|truncatechars:60  }}</h3></a>
                    <h4>Created: {{ answer.date_created }}</h4>
                </div>
            {% endfor %}
        </div>
    </div>
</div>
<div class="col-md-4">
    <a class="btn btn-link" href="{% url 'accounts:update' request.user.pk %}"><h4>Update account</h4></a>
    <a class="btn btn-link" href="{% url 'accounts:delete' request.user.pk %}"><h4>Delete account</h4></a>
</div>
<div class="col-md-4">
    <a class="btn btn-link" href="{% url 'accounts:user_questions' request.user.pk %}"><h4>Your questions</h4></a>
</div>
<div class="col-md-4">
    <a class="btn btn-link" href="{% url 'accounts:user_answers' request.user.pk %}"><h4>Your answers</h4></a>
</div>
{% endblock content %}

QuestionsAnswers/templates/accounts/update.html
{% extends 'base.html' %}

{% block title %} Update account{% endblock title %}

{% block content %}
<div class="col-md-6 col-md-offset-3">
<form class="form-horizontal" enctype="multipart/form-data" method="post">
    {% csrf_token %}
    {% for field in form %}
        {% for error in field.errors %}
        <div class="alert alert-warning alert-dismissible form-width" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times</span>
            </button>
            <strong>Error: </strong>{{ error }}
        </div>
        {% endfor %}
        {{ field.label_tag }}
        <span class="help-text text-info">{{ field.help_text }}</span>
        <div class="form-input">
            {{ field }}
        </div>
    {% endfor %}
    <input class="btn btn-default" value="Save" type="submit">
    <a class="btn btn-link" href="{% url 'accounts:detail' request.user.pk %}" >Back</a>
</form>
</div>
{% endblock content %}

QuestionsAnswers/templates/accounts/user_answers.html
{% extends 'base.html' %}

{% block content %}
<h1>Your answers</h1>
<hr>
<div class="col-md-12">
<div class="col-md-8">
{% for answer in answer_list %}
  <div class="quest-info">
    <a href="{% url 'questions:detail' answer.question_id.pk %}">{{ answer.question_id.title|truncatechars:80 }}</a>
    <div>
      {{ answer.question_id.text|truncatechars:200 }}
    </div>
    <div>
      <h5><strong>You answered:</strong></h5>
      {{ answer.text|truncatechars:200 }}
    </div>
    <div align="right" class="quest-username"><a href="#">{{ answer.user_id.username }}</a></div>
    <div align="right">
      <img class="quest-avatar" src="{{ answer.user_id.get_avatar_url }}" width="60" height="60">
    </div>
    <p class="quest-time" title="{{ quest.date_cteated }}">
      answered {{ answer.date_created|timesince }} ago
    </p>
  </div>
{% endfor %}
</div>
<div class="col-md-4" style="height:100%;">
<nav data-spy="affix" data-offset-top="60" data-offset-bottom="60">
  <ul>
    <li class="extra-li">
      <a href="{% url 'accounts:detail' request.user.pk %}"><h4>Account</h4></a>
    </li>
    <li class="extra-li">
      <a href="{% url 'accounts:user_questions' request.user.pk %}"><h4>All your questions</h4></a>
    </li>
    <li class="extra-li">
      <a href="{% url 'questions:all' %}"><h4>All questions</h4></a>
    </li>
    <li class="extra-li">
      <a href="{% url 'questions:create' %}"><h4>Create new question</h4></a>
    </li>
  </ul>
</nav>
</div>
</div>
{% if is_paginated %}
<nav>
    <ul class="pagination">
    {% if page_obj.has_previous %}
        <li>
        <a href="?page={{ page_obj.previous_page_number }}">
            <span>Previous</span>
        </a>
        </li>
    {% else %}
        <li class="disabled">
        <a href="#">
            <span>Previous</span>
        </a>
        </li>
    {% endif %}

    {% for page in paginator.page_range %}
        <li {% if page == page_obj.number %}class="active"{% endif %}>
        <a href="?page={{ page }}">{{ page }}</a>
        </li>
    {% endfor %}

    {% if page_obj.has_next %}
        <li>
        <a href="?page={{ page_obj.next_page_number }}">
            <span>Next</span>
        </a>
        </li>
    {% else %}
        <li {% if not page_obj.has_next %}class="disabled"{% endif %}>
        <a href="#">
            <span>Next</span>
        </a>
        </li>
    {% endif %}
    </ul>
</nav>
{% endif %}
{% endblock content %}

QuestionsAnswers/templates/accounts/user_questions.html
{% extends 'base.html' %}

{% block content %}
<h1 >Your questions</h1>
<hr>
<div class="col-md-12">
<div class="col-md-8">
{% for quest in question_list %}
  <div class="quest-info">
    <a href="{% url 'questions:detail' quest.pk %}">{{ quest.title|truncatechars:80 }}</a>
    <div>
      {{ quest.text|truncatechars:200 }}
    </div>
    <div align="right" class="quest-username"><a href="#">{{ quest.user_id.username }}</a></div>
    <div align="right">
      <img class="quest-avatar" src="{{ quest.user_id.get_avatar_url }}" width="60" height="60">
    </div>
    <p class="quest-time" title="{{ quest.date_cteated }}">
      asked {{ quest.date_created|timesince }} ago
    </p>
  </div>
{% endfor %}
</div>
<div class="col-md-4" style="height:100%;">
<nav data-spy="affix" data-offset-top="60" data-offset-bottom="60">
  <ul>
    <li class="extra-li">
      <a href="{% url 'accounts:detail' request.user.pk %}"><h4>Account</h4></a>
    </li>
    <li class="extra-li">
      <a href="{% url 'questions:all' %}"><h4>All questions</h4></a>
    </li>
    <li class="extra-li">
      <a href="{% url 'questions:create' %}"><h4>Create new question</h4></a>
    </li>
    <li class="extra-li">
      <a href="{% url 'accounts:user_answers' request.user.pk %}"><h4>All your answers</h4></a>
    </li>
  </ul>
</nav>
</div>
</div>
{% if is_paginated %}
<nav>
    <ul class="pagination">
    {% if page_obj.has_previous %}
        <li>
        <a href="?page={{ page_obj.previous_page_number }}">
            <span>Previous</span>
        </a>
        </li>
    {% else %}
        <li class="disabled">
        <a href="#">
            <span>Previous</span>
        </a>
        </li>
    {% endif %}

    {% for page in paginator.page_range %}
        <li {% if page == page_obj.number %}class="active"{% endif %}>
        <a href="?page={{ page }}">{{ page }}</a>
        </li>
    {% endfor %}

    {% if page_obj.has_next %}
        <li>
        <a href="?page={{ page_obj.next_page_number }}">
            <span>Next</span>
        </a>
        </li>
    {% else %}
        <li {% if not page_obj.has_next %}class="disabled"{% endif %}>
        <a href="#">
            <span>Next</span>
        </a>
        </li>
    {% endif %}
    </ul>
</nav>
{% endif %}
{% endblock content %}