QuestionsAnswers/QuestionsAnswers/urls.py
from django.conf.urls import url, include, static
from django.contrib import admin
from django.conf import settings


urlpatterns = [
    # admin site
    url(r'^admin/', admin.site.urls, name='admin'),
    # homepage
    url(r'^', include('apps.homepage.urls'), name='homepage'),
    # authentication
    url(r'^auth/', include('apps.authentication.urls'), name='authentication'),
    # users
    url(r'^users/', include('apps.accounts.urls'), name='users'),
    # questions
    url(r'^questions/', include('apps.questions.urls'), name='questions'),
    # questions and answers
    url(r'^questions/(?P<question>\d+)/answers/', include('apps.answers.urls'), name='answers'),
] + static.static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

QuestionsAnswers/apps/accounts/urls.py
from django.conf.urls import url, include
from .views import AccountDetail, AccountUpdate, AccountDelete, ListUserAnswers, \
    ListUserQuestions

app_name = 'accounts'

urlpatterns = [
    # update, delete account, pk=id
    url(r'(?P<pk>\d+)/update/$', AccountUpdate.as_view(), name='update'),
    url(r'(?P<pk>\d+)/delete/$', AccountDelete.as_view(), name='delete'),
    # detail view account
    url(r'(?P<pk>\d+)/$', AccountDetail.as_view(), name='detail'),
    # user answers
    url(r'^(?P<pk>\d+)/answers/$', ListUserAnswers.as_view(), name='user_answers'),
    # user questions
    url(r'^(?P<pk>\d+)/questions/$', ListUserQuestions.as_view(), name='user_questions'),
]

QuestionsAnswers/apps/authentication/urls.py
from django.conf.urls import url
from .views import CreateUser, LoginUser, logout_user

app_name = 'authentication'

urlpatterns = [
    # create account, registration
    url(r'create/$', CreateUser.as_view(), name='register'),
    # login
    url(r'login/$', LoginUser.as_view(), name='login'),
    # logout
    url(r'logout/$', logout_user, name='logout'),
]

QuestionsAnswers/apps/homepage/urls.py
from django.conf.urls import url, include
from .views import HomepageView

app_name = 'homepage'

urlpatterns = [
    url(r'^$', HomepageView.as_view(), name='homepage'),
]

QuestionsAnswers/templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}
<head>
    <meta charset="utf8">
    <title>{% block title %}{% endblock title %}</title>
    <!-- Get bootstrap 3.3.7 from cdn-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <!-- Extra head -->
    {% block head %}
    {% endblock head %}
</head>
<body>
    <!-- navbar -->
    <nav class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'homepage:homepage' %}">Home</a>
            </div>
            <div class="navbar-right">
                {% if request.user.is_authenticated %}
                    <div class="username" style="display:inline-block;">
                        <span><a class="btn btn-link" href="{% url 'accounts:detail' request.user.pk %}">
                            <strong>{{ request.user.username|truncatechars:20 }}</strong>
                        </a></span>
                    </div>
                    <div style="display:inline-block;">
                        <img class="img img-circle avatar" src="{{ request.user.get_avatar_url }}">
                    </div>
                    <a class="btn btn-primary" href="{% url 'authentication:logout' %}" style="margin:5px;">Logout</a>
                {% else %}
                <a class="btn btn-info" href="{% url 'authentication:login' %}" style="margin:5px;">Login</a>
                <a class="btn btn-primary" href="{% url 'authentication:register' %}" style="margin:5px;">Register</a>
                {% endif %}
            </div>
        </div>
    </nav>
    <!-- Extra navbar -->
    {% block navbar %}
    {% endblock navbar %}
    <!-- content webpage-->
    <div class="container">
    <!-- Extra content -->
    {% block content %}
    {% endblock content %}
    </div>
    <!-- footer -->
    {% block footer %}
    {% endblock footer %}
    <!-- Scripts -->
    <!-- Jquery 3.2.1 from Google cnd -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js">
    </script>
    <!-- Bootstrap scripts from cnd -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous">
    </script>
    <!-- Extra scripts -->
    {% block script %}
    {% endblock script %}
</body>
</html>