QuestionsAnswers/QuestionsAnswers/urls.py
from django.conf.urls import url, include, static
from django.contrib import admin
from django.conf import settings


urlpatterns = [
    # admin site
    url(r'^admin/', admin.site.urls, name='admin'),
    # homepage
    url(r'^', include('apps.homepage.urls'), name='homepage'),
    # authentication
    url(r'^auth/', include('apps.authentication.urls'), name='authentication'),
    # users
    url(r'^users/', include('apps.accounts.urls'), name='users'),
    # questions
    url(r'^questions/', include('apps.questions.urls'), name='questions'),
    # questions and answers
    url(r'^questions/(?P<question>\d+)/answers/', include('apps.answers.urls'), name='answers'),
] + static.static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

QuestionsAnswers/apps/accounts/urls.py
from django.conf.urls import url, include
from .views import AccountDetail, AccountUpdate, AccountDelete, ListUserAnswers, \
    ListUserQuestions

app_name = 'accounts'

urlpatterns = [
    # update, delete account, pk=id
    url(r'(?P<pk>\d+)/update/$', AccountUpdate.as_view(), name='update'),
    url(r'(?P<pk>\d+)/delete/$', AccountDelete.as_view(), name='delete'),
    # detail view account
    url(r'(?P<pk>\d+)/$', AccountDetail.as_view(), name='detail'),
    # user answers
    url(r'^(?P<pk>\d+)/answers/$', ListUserAnswers.as_view(), name='user_answers'),
    # user questions
    url(r'^(?P<pk>\d+)/questions/$', ListUserQuestions.as_view(), name='user_questions'),
]

QuestionsAnswers/apps/answers/urls.py
from django.conf.urls import url
from .views import CreateAnswer, UpdateAnswer, DeleteAnswer


app_name = 'answers'
urlpatterns = [
    # create answer
    url(r'^create/$', CreateAnswer.as_view(), name='create'),
    # update answer
    url(r'^(?P<answer>\d+)/update/$', UpdateAnswer.as_view(), name='update'),
    # delete answer
    url(r'^(?P<answer>\d+)/delete/$', DeleteAnswer.as_view(), name='delete'),

]

QuestionsAnswers/apps/authentication/urls.py
from django.conf.urls import url
from .views import CreateUser, LoginUser, logout_user

app_name = 'authentication'

urlpatterns = [
    # create account, registration
    url(r'create/$', CreateUser.as_view(), name='register'),
    # login
    url(r'login/$', LoginUser.as_view(), name='login'),
    # logout
    url(r'logout/$', logout_user, name='logout'),
]

QuestionsAnswers/apps/questions/urls.py
from django.conf.urls import url
from .views import CreateQuestion, UpdateQuestion, DeleteQuestion, ListQuestions, DetailQuestion


app_name = 'questions'
urlpatterns = [
    # all questions
    url(r'^all/$', ListQuestions.as_view(), name='all'),
    # create question
    url(r'^create/$', CreateQuestion.as_view(), name='create'),
    # update question
    url(r'^(?P<question>\d+)/update/$', UpdateQuestion.as_view(), name='update'),
    # delete question
    url(r'^(?P<question>\d+)/delete/$', DeleteQuestion.as_view(), name='delete'),
    # detail question
    url(r'^(?P<question>\d+)/detail/$', DetailQuestion.as_view(), name='detail'),

]

QuestionsAnswers/apps/questions/models.py
from django.db import models
from django.conf import settings
from django.utils.translation import gettext_lazy as _


# question model
class Question(models.Model):
    # primary key
    id = models.AutoField(_('id'), auto_created=True, primary_key=True)
    # id to user object, who created this question
    user_id = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name=_('user id'),
                                db_column='user_id')
    # title of question
    title = models.CharField(_('title'), max_length=180, db_column='title',
                             help_text=_('Required. 180 character or fewer.'),
                             validators=[],
                             error_messages={
                                 'invalid': _('Enter a valid title.'),
                             })
    # text question
    text = models.TextField(_('text'), max_length=30000, db_column='text',
                            help_text=_('Required. 30000 characters limit. Ask a question.'),
                            validators=[],
                            error_messages={
                                'invalid': _('Your question not valid. Check text and try again.'),
                            })
    # date when questions was created
    date_created = models.DateTimeField(_('date created'), db_column='date_created', auto_now_add=True)

    class Meta:
        verbose_name = 'Questions'
        db_table = 'questions'

    # return str object. Example: Question №3 by Vasiliy
    def __str__(self):
        return 'Question №' + str(self.id) + ' by ' + str(self.user_id.username)

QuestionsAnswers/apps/questions/forms.py
from django import forms
from .models import Question


# create model form Question
class CreateQuestionForm(forms.ModelForm):

    class Meta:
        model = Question
        fields = ('title', 'text')
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control form-width'}),
            'text': forms.Textarea(attrs={'class': 'question-text'}),
        }


# update model form question
class UpdateQuestionForm(forms.ModelForm):

    class Meta:
        model = Question
        fields = ('title', 'text')
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control form-width'}),
            'text': forms.Textarea(attrs={'class': 'question-text'}),
        }

QuestionsAnswers/apps/questions/views.py
from django.shortcuts import redirect, Http404
from django.core.urlresolvers import resolve
from django.core.exceptions import ObjectDoesNotExist
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, DetailView, UpdateView, ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.translation import gettext_lazy as _
from .forms import CreateQuestionForm, UpdateQuestionForm
from ..accounts.models import User
from ..answers.models import Answer
from .models import Question


# mixin for dispatch
# override dispatch method for redirect
class QuestionDispatchMixin(object):
    def dispatch(self, request, *args, **kwargs):
        # try get question
        try:
            quest = Question.objects.get(id=kwargs['question'])
            # user == request.user
            if quest.user_id.id == request.user.id:
                return super().dispatch(request, *args, **kwargs)
            else:
                # Example:
                # this happened, if url - /questions/9/ change to /questions/10/ but user_id != request.user.id
                # raise 404
                # this method only fo questions
                raise Http404
        # if not question
        except ObjectDoesNotExist:
            raise Http404


# create view with login required
class CreateQuestion(CreateView, LoginRequiredMixin):
    template_name = 'questions/create.html'
    form_class = CreateQuestionForm
    success_url = 'questions:detail'
    # login required settings
    login_url = '/'
    redirect_field_name = None

    # override form valid for set user object to user_id field of questions
    def form_valid(self, form):
        # get user object
        user = User.objects.get(id=self.request.user.id)
        # set this in form
        form.instance.user_id = user
        return super().form_valid(form)

    # override func success url
    def get_success_url(self):
        # return success url with pk
        return reverse_lazy(self.success_url, kwargs={'question': self.object.pk})


# update view with login required
class UpdateQuestion(QuestionDispatchMixin, UpdateView, LoginRequiredMixin):
    template_name = 'questions/update.html'
    form_class = UpdateQuestionForm
    model = Question
    success_url = 'questions:update'
    # get args from url
    pk_url_kwarg = 'question'
    # login required settings
    login_url = '/'
    redirect_field_name = None

    # override func success url
    def get_success_url(self):
        # return success url with pk
        return reverse_lazy(self.success_url, kwargs={'question': self.object.pk})


# delete view with login required
class DeleteQuestion(QuestionDispatchMixin, DeleteView, LoginRequiredMixin):
    template_name = 'questions/delete.html'
    model = Question
    success_url = 'accounts:user_questions'
    # get args from url
    pk_url_kwarg = 'question'
    # login required settings
    login_url = '/'
    redirect_field_name = None

    # override post method
    def post(self, request, *args, **kwargs):
        # set self.object
        self.object = self.get_object()
        # get user object
        user = User.objects.get(id=request.user.pk)
        # check password for user and if true return delete method
        if user.check_password(request.POST.get('password_confirm')):
            return self.delete(request, *args, **kwargs)
        else:
            # set error to context and response template
            context = super().get_context_data(**kwargs)
            context['error'] = _('Invalid password')
            return self.render_to_response(context=context)

    # override func success url
    def get_success_url(self):
        # return success url with pk
        return reverse_lazy(self.success_url, kwargs={'pk': self.object.user_id.pk})


# \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\

# list all questions
class ListQuestions(ListView):
    template_name = 'questions/all.html'
    model = Question
    paginate_by = 6

    # get queryset
    def get_queryset(self):
        return self.model.objects.all().order_by('-date_created')


# list detail selected question
class DetailQuestion(DetailView):
    template_name = 'questions/detail.html'
    model = Question
    # get args from url
    pk_url_kwarg = 'question'

    # override context_data method
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        question = Question.objects.get(id=self.kwargs['question'])
        # add answers in context
        context['answers'] = list(Answer.objects.filter(question_id=question.id))
        print(context, question.id)
        return context


# ////////////////////////////////////////////////////

QuestionsAnswers/templates/questions/all.html
{% extends 'base.html' %}

{% block content %}
<h1>Questions</h1>
<hr>
<div class="col-md-12">
<div class="col-md-8">
{% for quest in question_list %}
  <div class="quest-info">
    <a href="{% url 'questions:detail' quest.pk %}">{{ quest.title|truncatechars:80 }}</a>
    <div>
      {{ quest.text|truncatechars:200 }}
    </div>
    <div align="right" class="quest-username"><a href="#">{{ quest.user_id.username }}</a></div>
    <div align="right">
      <img class="quest-avatar" src="{{ quest.user_id.get_avatar_url }}" width="60" height="60">
    </div>
    <p class="quest-time" title="{{ quest.date_cteated }}">
      asked {{ quest.date_created|timesince }} ago
    </p>
  </div>
{% endfor %}
</div>
<div class="col-md-4" >

<nav data-spy="affix" data-offset-top="60" data-offset-bottom="60">
  <ul>
    {% if request.user.is_authenticated %}
    <li class="extra-li">
      <a href="{% url 'accounts:detail' request.user.pk %}"><h4>Account</h4></a>
    </li>
    <li class="extra-li">
      <a href="{% url 'accounts:user_questions' request.user.pk %}"><h4>All your questions</h4></a>
    </li>
    <li class="extra-li">
      <a href="{% url 'accounts:user_answers' request.user.pk %}"><h4>All your answers</h4></a>
    </li>
    <li class="extra-li">
      <a href="{% url 'questions:create' %}"><h4>Create new question</h4></a>
    </li>
    {% else %}
    <li class="extra-li">
        <a href="{% url 'authentication:login' %}"><h4>Login</h4></a>
    </li>
    <li class="extra-li">
        <a href="{% url 'authentication:register' %}"><h4>Registration</h4></a>
    </li>
  </ul>
</nav>
{% endif %}

</div>
</div>
{% if is_paginated %}
<nav class="question-paginated">
    <ul class="pagination">
    {% if page_obj.has_previous %}
        <li>
        <a href="?page={{ page_obj.previous_page_number }}">
            <span>Previous</span>
        </a>
        </li>
    {% else %}
        <li class="disabled">
        <a href="#">
            <span>Previous</span>
        </a>
        </li>
    {% endif %}

    {% for page in paginator.page_range %}
        <li {% if page == page_obj.number %}class="active"{% endif %}>
        <a href="?page={{ page }}">{{ page }}</a>
        </li>
    {% endfor %}

    {% if page_obj.has_next %}
        <li>
        <a href="?page={{ page_obj.next_page_number }}">
            <span>Next</span>
        </a>
        </li>
    {% else %}
        <li {% if not page_obj.has_next %}class="disabled"{% endif %}>
        <a href="#">
            <span>Next</span>
        </a>
        </li>
    {% endif %}
    </ul>
</nav>
{% endif %}

{% endblock content %}

QuestionsAnswers/templates/questions/create.html
{% extends 'base.html' %}

{% block title %}Create question{% endblock title %}

{% block content %}
<div class="col-md-7 col-md-offset-2">
<form class="form-signin" method="post" enctype="multipart/form-data">
        <!-- Token django CSRF -->
        {% csrf_token %}
        {% for field in form %}
        {% for error in field.errors %}
        <div class="alert alert-warning alert-dismissible form-width" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times</span>
            </button>
            <strong>Error: </strong>{{ error }}
        </div>
        {% endfor %}
        {{ field.label_tag }}
        <span class="help-text text-info">{{ field.help_text }}</span>
        <div class="form-input">
            {{ field }}
        </div>
        {% endfor %}
        <input class="btn btn-default" value="Save" type="submit">
        <a class="btn btn-link" href="{% url 'accounts:detail' request.user.pk %}" >Back</a>
</form>
</div>
{% endblock content %}

QuestionsAnswers/templates/questions/delete.html
{% extends 'base.html' %}

{% block title %}Delete question{% endblock title %}

{% block content %}
<div class="col-md-6 col-md-offset-3">
<form action="" method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete "{{ object.title|truncatechars:60 }}"?</p>
        {% if error %}
            <div class="alert alert-warning alert-dismissible form-width" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times</span>
                </button>
                <strong>Error: </strong>{{ error }}
            </div>
        {% endif %}
        <label for="id_password">Password:</label>
        <span class="help-text text-info">Input your password</span>
        <div class="form-input">
            <input class="form-control form-width" type="password" id="id_password" name="password_confirm">
        </div>
        <input class="btn btn-default" type="submit" value="Confirm" />
        <a class="btn btn-link" href="{% url 'questions:detail' object.pk %}" >Back</a>
</form>
</div>
{% endblock content %}

QuestionsAnswers/templates/questions/detail.html
{% extends 'base.html' %}

{% block content %}

<div class="col-md-12">
    <h1>{{ question.title }}</h1>
    <hr>
</div>
<div class="col-md-8">
<span class="long-text">
{% autoescape off %}
    {{ question.text }}
{% endautoescape %}
</span>
<div align="right" class="quest-username"><a href="#">{{ question.user_id.username }}</a></div>
<div align="right">
     <img class="quest-avatar" src="{{ question.user_id.get_avatar_url }}" width="60" height="60">
</div>
<p class="quest-time" title="{{ quest.date_cteated }}">
      asked {{ question.date_created|timesince }} ago
</p>
<div style="padding-top: 90px;">
<h2>Answers</h2>
<hr>
{% for answer in answers %}
   <span class="long-text">
    {% autoescape off %}
        {{ answer.text }}
    {% endautoescape %}
    </span>
        <div align="right" class="quest-username"><a href="#">{{ answer.user_id.username }}</a></div>
        <div align="right">
            <img class="quest-avatar" src="{{ answer.user_id.get_avatar_url }}" width="60" height="60">
        </div>
    <p class="quest-time" title="{{ answer.date_cteated }}">
      answered {{ answer.date_created|timesince }} ago
    </p>
    {% if request.user.pk == answer.user_id.id %}
        <a class="btn btn-link" href="{% url 'answers:update' answer.question_id.pk answer.pk %}"><h4>Update answer</h4></a>
        <a class="btn btn-link" href="{% url 'answers:delete' answer.question_id.pk answer.pk %}"><h4>Delete answer</h4></a>
    {% endif %}
    <hr>
{% endfor %}
</div>
</div>
<div class="col-md-4" style="height:100%;">
<nav data-spy="affix" data-offset-top="60" data-offset-bottom="60">
  <ul>
    {% if request.user.is_authenticated %}
        {% if question.user_id.pk == request.user.pk %}
            <li class="extra-li">
              <a href="{% url 'questions:update' question.id %}"><h4>Update Question</h4></a>
            </li>
            <li class="extra-li">
              <a href="{% url 'questions:delete' question.id %}"><h4>Delete Question</h4></a>
            </li>
            <hr>
        {% endif %}
    <li class="extra-li">
      <a href="{% url 'answers:create' question.id %}"><h4>Create answer</h4></a>
    </li>
    <hr>
    <li class="extra-li">
      <a href="{% url 'accounts:detail' request.user.pk %}"><h4>Account</h4></a>
    </li>
    <li class="extra-li">
      <a href="{% url 'accounts:user_questions' request.user.pk %}"><h4>All your questions</h4></a>
    </li>
    <li class="extra-li">
      <a href="{% url 'questions:all' %}"><h4>All questions</h4></a>
    </li>
    <li class="extra-li">
      <a href="{% url 'questions:create' %}"><h4>Create new question</h4></a>
    </li>
    {% else %}
    <li class="extra-li">
      <a href="{% url 'questions:all' %}"><h4>All questions</h4></a>
    </li>
    <li class="extra-li">
      <a href="{% url 'authentication:register' %}"><h4>Registration</h4></a>
    </li>
    <li class="extra-li">
      <a href="{% url 'authentication:login' %}"><h4>Login</h4></a>
    </li>
    {% endif %}
  </ul>
</nav>
</div>
{% endblock content %}

QuestionsAnswers/templates/questions/update.html
{% extends 'base.html' %}

{% block title %} Update question{% endblock title %}

{% block content %}
<div class="col-md-7 col-md-offset-2">
<form class="form-horizontal" enctype="multipart/form-data" method="post">
    {% csrf_token %}
    {% for field in form %}
        {% for error in field.errors %}
        <div class="alert alert-warning alert-dismissible form-width" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times</span>
            </button>
            <strong>Error: </strong>{{ error }}
        </div>
        {% endfor %}
        {{ field.label_tag }}
        <span class="help-text text-info">{{ field.help_text }}</span>
        <div class="form-input">
            {{ field }}
        </div>
        {% endfor %}
        <input class="btn btn-default" value="Save" type="submit">
        <a class="btn btn-link" href="{% url 'questions:detail' object.pk %}" >Back</a>
</form>
</div>
{% endblock content %}