QuestionsAnswers/QuestionsAnswers/urls.py
from django.conf.urls import url, include, static
from django.contrib import admin
from django.conf import settings


urlpatterns = [
    # admin site
    url(r'^admin/', admin.site.urls, name='admin'),
    # homepage
    url(r'^', include('apps.homepage.urls'), name='homepage'),
    # authentication
    url(r'^auth/', include('apps.authentication.urls'), name='authentication'),
    # users
    url(r'^users/', include('apps.accounts.urls'), name='users'),
    # questions
    url(r'^questions/', include('apps.questions.urls'), name='questions'),
    # questions and answers
    url(r'^questions/(?P<question>\d+)/answers/', include('apps.answers.urls'), name='answers'),
] + static.static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

QuestionsAnswers/apps/accounts/urls.py
from django.conf.urls import url, include
from .views import AccountDetail, AccountUpdate, AccountDelete, ListUserAnswers, \
    ListUserQuestions

app_name = 'accounts'

urlpatterns = [
    # update, delete account, pk=id
    url(r'(?P<pk>\d+)/update/$', AccountUpdate.as_view(), name='update'),
    url(r'(?P<pk>\d+)/delete/$', AccountDelete.as_view(), name='delete'),
    # detail view account
    url(r'(?P<pk>\d+)/$', AccountDetail.as_view(), name='detail'),
    # user answers
    url(r'^(?P<pk>\d+)/answers/$', ListUserAnswers.as_view(), name='user_answers'),
    # user questions
    url(r'^(?P<pk>\d+)/questions/$', ListUserQuestions.as_view(), name='user_questions'),
]

QuestionsAnswers/apps/authentication/urls.py
from django.conf.urls import url
from .views import CreateUser, LoginUser, logout_user

app_name = 'authentication'

urlpatterns = [
    # create account, registration
    url(r'create/$', CreateUser.as_view(), name='register'),
    # login
    url(r'login/$', LoginUser.as_view(), name='login'),
    # logout
    url(r'logout/$', logout_user, name='logout'),
]

QuestionsAnswers/apps/homepage/urls.py
from django.conf.urls import url, include
from .views import HomepageView

app_name = 'homepage'

urlpatterns = [
    url(r'^$', HomepageView.as_view(), name='homepage'),
]

QuestionsAnswers/apps/questions/urls.py
from django.conf.urls import url
from .views import CreateQuestion, UpdateQuestion, DeleteQuestion, ListQuestions, DetailQuestion


app_name = 'questions'
urlpatterns = [
    # all questions
    url(r'^all/$', ListQuestions.as_view(), name='all'),
    # create question
    url(r'^create/$', CreateQuestion.as_view(), name='create'),
    # update question
    url(r'^(?P<question>\d+)/update/$', UpdateQuestion.as_view(), name='update'),
    # delete question
    url(r'^(?P<question>\d+)/delete/$', DeleteQuestion.as_view(), name='delete'),
    # detail question
    url(r'^(?P<question>\d+)/detail/$', DetailQuestion.as_view(), name='detail'),

]

QuestionsAnswers/apps/homepage/models.py
from django.db import models

# Create your models here.

QuestionsAnswers/apps/homepage/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from ..questions.models import Question

# Create your views here.


# Homepage view
class HomepageView(TemplateView):
    template_name = 'homepage/homepage.html'

    # get questions list limit 10
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['questions'] = list(Question.objects.all().order_by('-date_created')[:10])
        return context

QuestionsAnswers/templates/homepage/homepage.html
{% extends 'base.html' %}

{% block title %}Homepage{% endblock title %}


{% block content %}
<div class="col-md-9 col-md-offset-1">
    <h2>LINKS</h2>
    <hr>
    {% if request.user.is_authenticated %}
    <a href="{% url 'accounts:detail' request.user.pk %}"><h5 style="display:inline-block; padding:4px;">Account</h5></a>
    <a href="{% url 'accounts:user_questions' request.user.pk %}"><h5 style="display:inline-block; padding:4px;">All your questions</h5></a>
    <a href="{% url 'accounts:user_answers' request.user.pk %}"><h5 style="display:inline-block; padding:4px;">All your answers</h5></a>
    {% else %}
    <a href="{% url 'authentication:login' %}"><h5>Login</h5></a>
    <a href="{% url 'authentication:register' %}"><h5>Registration</h5></a>
    {% endif %}
    <hr>
</div>
<div class="col-md-9 col-md-offset-1">
        <h2>10 Last questions</h2>
        <div class="homepage-area-question">
            {% for quest in questions %}
                <div class="questions">
                    <a href="{% url 'questions:detail' quest.pk %}"><h3>{{ quest.title|truncatechars:60 }}</h3></a>
                    <div>
                        {{ quest.text|truncatechars:300 }}
                    </div>
                    <div align="right" class="quest-username"><a href="#">{{ quest.user_id.username }}</a></div>
                    <div align="right">
                        <img class="quest-avatar" src="{{ quest.user_id.get_avatar_url }}" width="60" height="60">
                    </div>
                    <h4>Created: {{ quest.date_created }}</h4>
                </div>
            {% endfor %}
            <hr>
            <a class="btn btn-link" href="{% url 'questions:all' %}"><h2>All questions</h2></a>
        </div>
</div>

{% endblock content %}